// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTask(arg1:string,arg2:string):Promise<models.Task>;

export function DeleteTask(arg1:number):Promise<models.Task>;

export function GetTaskById(arg1:number):Promise<models.Task>;

export function GetTasks():Promise<Array<models.Task>>;

export function UpdateTaskStatus(arg1:number):Promise<models.Task>;
